# .github/workflows/release.yaml
name: build-releases
on: 
  release:
    types: [created]

jobs:
  release-linux-amd64:
    name: release linux/amd64
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goarch: [ amd64, arm64, arm ]
    steps:
    - uses: actions/checkout@v2
    - uses: wangyoucao577/go-release-action@v1.19
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: linux
        goarch: ${{ matrix.goarch }}
        goversion: "https://golang.org/dl/go1.16.6.linux-amd64.tar.gz"
        overwrite: TRUE
        build_command: CGO_ENABLED=0 go build
